version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MYSQL_DB=MilitaryManager
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=myapp_db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: MilitaryManager
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=development
    command: npm start  # Avvia il server di sviluppo React
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  mysql-data:
